### ISSUE TITLE
Does Direktiv have any requirements for the version of knative

### ISSUE THREAD

**Issue by lianggengdino** [direktiv/direktiv-charts#32]
### Just ask what you want to know about vorteil
Now I install latest Direktiv by helm,the chart version is 0.1.19.Can I use version 1.3.2 of knative?
If not ,what lowest version of knative I can use?

**Comment by jensg-st** [comment]
Hi, I don't know if 1.3.2 works. We have instances running with 1.5 so that works for sure. The only new-ish feature we are using are the shared directories. I don't know when that had been introduced. But looking at the timelines of releases it should be in 1.3.2 and therefore it should work too.

**Comment by lianggengdino** [comment]
> Hi, I don't know if 1.3.2 works. We have instances running with 1.5 so that works for sure. The only new-ish feature we are using are the shared directories. I don't know when that had been introduced. But looking at the timelines of releases it should be in 1.3.2 and therefore it should work too.

ok,thx.
